name: sadaf
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android_html_widget

  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type


  flutter_bloc: any

  #  map_package:
  #    path: ../../packages/map_package

  #  dartz: ^0.10.1
  model_viewer_plus: ^1.7.0
  hive: any
  hive_flutter: any
  pod_player: ^0.2.1
  equatable: ^2.0.5
  flutter_holo_date_picker: ^1.1.3
  flutter_rating_bar: any
  google_maps_flutter: ^2.5.3
  get_it: any
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  group_button:
  shared_preferences: any
  bloc: ^8.1.2
  lottie: any
  flutter_screenutil: ^5.9.0
  pinput: ^2.2.21
  carousel_slider: any
  image_picker: any
  url_launcher: any
  logger: ^1.1.0
  dropdown_button2: ^2.3.9
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  geolocator: any
  intl: any
  flutter_local_notifications: ^16.3.1+1
  package_info_plus: ^4.1.0
  webview_flutter: ^4.4.4
  awesome_dialog: any
  google_polyline_algorithm: any
  widget_to_marker: any
  infinite_scroll_pagination: ^4.0.0
  path_provider: ^2.1.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lotties/
    - assets/sounds/
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: cairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: cairoSemiBold
      fonts:
        - asset: assets/fonts/cairo_semi_bold.ttf
flutter_intl:
  enabled: true
